Adz.User.CMS/Controllers/ReportingController.cs
using Adz.BLL.Lib;
using Adz.User.CMS.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Adz.User.CMS.Controllers
{
    public class ReportingController : BaseAdminController
    {
        public ICampaignService campaignservice = new CampaignService();

        public ActionResult AdsPerformanceUsage()
        {
            ViewModels.AdsPerformanceUsageVM model = new ViewModels.AdsPerformanceUsageVM();

            //model.CampaignHistories = new List<CampaignModel.CampaignHistory>();
            model.CampaignHistoryGroup = new List<CampaignModel.CampaignHistoryGroup>();

            //foreach (var v in campaignservice.GetCampaignHistory().Result)
            //{
            //    model.CampaignHistories.Add(new CampaignModel.CampaignHistory() { Campaign = new CampaignModel.Campaign() { CampaignId = v.Campaign.CampaignId, Name = v.Campaign.Name }, User = new UserModel.User() { UserId = v.User.UserId, Email = v.User.Email }, ViewTime = v.ViewTime, Gender = v.Gender, Latitude = v.Latitude, Longitude = v.Longitude });
            //}
            foreach (var v in campaignservice.GetCampaignHistoryGroup().Result)
            {
                model.CampaignHistoryGroup.Add(new CampaignModel.CampaignHistoryGroup() { Campaign = new CampaignModel.Campaign() { CampaignId = v.Campaign.CampaignId, Name = v.Campaign.Name }, Views = v.Views, LastViewTime = v.LastViewTime, Clicks = v.Clicks, LastClickTime = v.LastClickTime });
            }

            return View(model);
        }
        
        public ActionResult AdsViewPerformanceUsage_Read([DataSourceRequest] DataSourceRequest request)
        {
            var newlistR = new List<CampaignModel.CampaignHistory>();
            foreach (var v in campaignservice.GetCampaignHistory((int)CampaignHistoryAction.View).Result)
            {
                newlistR.Add(new CampaignModel.CampaignHistory() { Campaign = new CampaignModel.Campaign() { CampaignId = v.Campaign.CampaignId, Name = v.Campaign.Name }, User = new UserModel.User() { UserId = v.User.UserId, Email = v.User.Email }, DateTime = v.DateTime, Gender = v.Gender == 1 ? "Male" : v.Gender == 2 ? "Female" : "Undisclosed", Latitude = v.Latitude, Longitude = v.Longitude });
            }
            IEnumerable<CampaignModel.CampaignHistory> ienuList = newlistR;
            var result = ienuList.ToDataSourceResult(request);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AdsClickPerformanceUsage_Read([DataSourceRequest] DataSourceRequest request)
        {
            var newlistR = new List<CampaignModel.CampaignHistory>();
            foreach (var v in campaignservice.GetCampaignHistory((int)CampaignHistoryAction.Click).Result)
            {
                newlistR.Add(new CampaignModel.CampaignHistory() { Campaign = new CampaignModel.Campaign() { CampaignId = v.Campaign.CampaignId, Name = v.Campaign.Name }, User = new UserModel.User() { UserId = v.User.UserId, Email = v.User.Email }, DateTime = v.DateTime, Gender = v.Gender == 1 ? "Male" : v.Gender == 2 ? "Female" : "Undisclosed", Latitude = v.Latitude, Longitude = v.Longitude });
            }
            IEnumerable<CampaignModel.CampaignHistory> ienuList = newlistR;
            var result = ienuList.ToDataSourceResult(request);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AdsPerfUsageByCampaign(int campaignId)
        {
            ViewModels.AdsPerformanceUsageVM model = new ViewModels.AdsPerformanceUsageVM();
            model.CampaignHistories = new List<CampaignModel.CampaignHistory>();
            foreach (var v in campaignservice.GetCampaignHistoryByCampaignId(campaignId, 0).Result)
            {
                model.CampaignHistories.Add(new CampaignModel.CampaignHistory() { Campaign = new CampaignModel.Campaign() { CampaignId = v.Campaign.CampaignId, Name = v.Campaign.Name }, User = new UserModel.User() { UserId = v.User.UserId, Email = v.User.Email }, DateTime = v.DateTime, Gender = v.Gender == 1 ? "Male" : v.Gender == 2 ? "Female" : "Undisclosed", Latitude = v.Latitude, Longitude = v.Longitude, Action = v.Action == 1 ? "View" : "Click" });
            }
            return View(model);
        }

        public ActionResult AdsPerformanceDetail(int CampaignId)
        {
            ViewBag.CampaignId = CampaignId;
            return View();
        }

        public ActionResult AdsPerformanceUsageDetail_Read([DataSourceRequest] DataSourceRequest request, int CampaignId)
        {
            var newlistR = new List<CampaignModel.CampaignHistory>();
            foreach (var v in campaignservice.GetCampaignHistoryByCampaignId(CampaignId, 0).Result)
            {
                int Age = -1;
                if (v.User.DateOfBirth > DateTime.MinValue)
                {
                    Age = DateTime.Today.Year - v.User.DateOfBirth.Year;
                    if (v.User.DateOfBirth > DateTime.Today.AddYears(-Age)) Age--;
                }
                newlistR.Add(new CampaignModel.CampaignHistory() { Campaign = new CampaignModel.Campaign() { CampaignId = v.Campaign.CampaignId, Name = v.Campaign.Name }, User = new UserModel.User() { UserId = v.User.UserId, Email = v.User.Email, Age = Age }, DateTime = v.DateTime, Gender = v.Gender == 1 ? "Male" : v.Gender == 2 ? "Female" : "Undisclosed", Latitude = v.Latitude, Longitude = v.Longitude, Action = v.Action == 1 ? "View" : ( v.Action == 2 ? "Click" : "N/A") });
            }
            IEnumerable<CampaignModel.CampaignHistory> ienuList = newlistR;
            var result = ienuList.ToDataSourceResult(request);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AdsPerformanceUsageDetailSummarize_Read([DataSourceRequest] DataSourceRequest request, int CampaignId)
        {
            var newlistR = new List<CampaignModel.CampaignHistoryGroupSummarize>();
            var listR = campaignservice.GetCampaignHistoryByCampaignId(CampaignId, 0).Result.Select(
                            x => new
                            {
                                Action = x.Action,
                                Date = x.DateTime.Date,
                                Hour = x.DateTime.AddMinutes(-1).Hour % 2 != 0 ? x.DateTime.AddMinutes(-1).Hour + 1 : x.DateTime.AddMinutes(-1).Hour
                            }
                        ).GroupBy(x => new { x.Date, x.Hour });
            foreach (var v in listR)
            {
                newlistR.Add(new CampaignModel.CampaignHistoryGroupSummarize() { Date = v.Key.Date, HourGroup = (v.Key.Hour - 2) + ":01 - " + v.Key.Hour + ":00", Views = v.Where(x => x.Action == 1).Count(), Clicks = v.Where(x => x.Action == 2).Count() });
            }
            IEnumerable<CampaignModel.CampaignHistoryGroupSummarize> ienuList = newlistR;
            var result = ienuList.ToDataSourceResult(request);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult FilterMenuCustomization_Genders()
        {
            List<String> Genders = new List<string>();
            Genders.Add("Male");
            Genders.Add("Female");
            Genders.Add("Undisclosed");
            return Json(Genders, JsonRequestBehavior.AllowGet);
        }

        public ActionResult FilterMenuCustomization_AgeGroup()
        {
            List<String> AgeGroup = new List<string>();
            AgeGroup.Add("0");
            AgeGroup.Add("10");
            AgeGroup.Add("20");
            AgeGroup.Add("30");
            AgeGroup.Add("40");
            AgeGroup.Add("50");
            return Json(AgeGroup, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AdsPerformanceUsageDetailGraph_Read([DataSourceRequest] DataSourceRequest request, int CampaignId)
        {
            List<CampaignModel.CampaignChart> model = new List<CampaignModel.CampaignChart>();

            var data = campaignservice.GetCampaignHistoryByCampaignId(CampaignId, 0).Result;

            for (int i = 7; i >= 1; i--)
            {
                DateTime iDate = DateTime.Now.AddDays(-i);
                int iViews = data.Where(d => d.DateTime.Day == iDate.Day && d.DateTime.Month == iDate.Month && d.DateTime.Year == iDate.Year && d.Action == 1).Count();
                int iClicks = data.Where(d => d.DateTime.Day == iDate.Day && d.DateTime.Month == iDate.Month && d.DateTime.Year == iDate.Year && d.Action == 2).Count();

                model.Add(new CampaignModel.CampaignChart() { Clicks = iClicks, Views = iViews, Date = iDate });
            }
            
            IEnumerable<CampaignModel.CampaignChart> chartData = model;
            return Json(chartData);
        }

        public ActionResult AdsPerformanceUsageDetailAgePie_Read([DataSourceRequest] DataSourceRequest request, int CampaignId)
        {
            List<CampaignModel.CampaignPieChart> model = new List<CampaignModel.CampaignPieChart>();
            int Year = DateTime.UtcNow.Year;

            int[] Count = {0,0,0,0,0,0,0};

            foreach(var v in campaignservice.GetCampaignHistoryByCampaignId(CampaignId, 0).Result)
            {
                if(Year - v.User.DateOfBirth.Year < 10)
                {
                    Count[1]++;
                }
                else if (Year - v.User.DateOfBirth.Year < 20)
                {
                    Count[2]++;
                }
                else if (Year - v.User.DateOfBirth.Year < 30)
                {
                    Count[3]++;
                }
                else if (Year - v.User.DateOfBirth.Year < 40)
                {
                    Count[4]++;
                }
                else if (Year - v.User.DateOfBirth.Year < 50)
                {
                    Count[5]++;

Adz.User.CMS/Views/Reporting/AdsPerfUsageByCampaign.cshtml
@model Adz.User.CMS.Models.ViewModels.AdsPerformanceUsageVM
@{
    Layout = "~/Views/Shared/_EmptyLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h3>Ads History Detail</h3><br/>
            <table class="table table-striped table-hover table-bordered">
                <thead>
                    <tr>
                        <th>Campaign Name</th>
                        <th>Date Time</th>
                        <th>User</th>
                        <th>Gender</th>
                        <th>Latitude</th>
                        <th>Longitude</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var v in Model.CampaignHistories)
                    {
                        <tr>
                            <td>@v.Campaign.Name</td>
                            <td>@v.DateTime</td>
                            <td>@v.User.Email</td>
                            <td>@v.Gender</td>
                            <td>@v.Latitude</td>
                            <td>@v.Longitude</td>
                            <td>@v.Action</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Adz.User.CMS/Views/Reporting/AdsPerformanceUsage.cshtml
@model Adz.User.CMS.Models.ViewModels.AdsPerformanceUsageVM
@{
    ViewBag.Title = "Ads Performance/Usage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@using Kendo.Mvc.UI
<script src="@Url.Content("~/Scripts/jquery.fancybox.js")" type="text/javascript"></script>
<link rel="stylesheet" href="@Url.Content("~/Content/fancy/jquery.fancybox.css")">
<script type="text/javascript">
    $(document).ready(function () {
        changeverticalnav(20);
        $(document).tooltip();
        $('.fancybox').fancybox();
    });
</script>

<div class="rightheader">
    <h1>Ads Performance/Usage</h1>
    <div class="pagelink">
        <a href="#">Admin Portal</a> /
        <a>Ads Performance/Usage</a>
    </div>
</div>

<div id="msgbox">
    @if (ViewBag.msg != null && ViewBag.msg != "")
    {
        <div class="alert alert-block alert-danger">
            <a class="close" data-dismiss="alert" href="#">X</a>
            <h4 class="alert-heading">Error</h4>
            @ViewBag.msg
        </div>
    }
</div>

<div class="rightcontent">
    <div class="rightrow">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                Ads Summary
                            </div>
                            <div class="panel-body">
                                <table class="table table-striped table-hover">
                                    <thead>
                                        <tr>
                                            <th>Campaign Name</th>
                                            <th>Views</th>
                                            <th>Last View</th>
                                            <th>Clicks</th>
                                            <th>Last Click</th>
                                            <th>Views Heat Map</th>
                                            <th>Clicks Heat Map</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var v in Model.CampaignHistoryGroup)
                                        {
                                            <tr>
                                                <td><a class="a-hand-cursor" href="@Url.Action("AdsPerformanceDetail", "Reporting")?CampaignId=@v.Campaign.CampaignId" @*onclick="fancybox(@v.Campaign.CampaignId)"*@>@v.Campaign.Name</a></td>
                                                <td>@v.Views</td>
                                                @if (v.Views > 0) { 
                                                    <td>@v.LastViewTime</td>
                                                }
                                                else
                                                {
                                                    <td>-</td>
                                                }
                                                <td>@v.Clicks</td>
                                                @if (v.Clicks > 0) { 
                                                    <td>@v.LastClickTime</td>
                                                }
                                                else
                                                {
                                                <td>-</td>
                                                }
                                                @if (v.Views > 0) {
                                                    <td><a class="a-hand-cursor" onclick="fancyboxHeatMap(@v.Campaign.CampaignId, 1)">View</a></td>
                                                }
                                                else
                                                {
                                                    <td>-</td>
                                                }
                                                @if (v.Clicks > 0) { 
                                                    <td><a class="a-hand-cursor" onclick="fancyboxHeatMap(@v.Campaign.CampaignId, 2)">View</a></td>
                                                }
                                                else
                                                {
                                                    <td>-</td>
                                                }
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                Ads Views History
                            </div>
                            <div class="panel-body" style="padding: 0;">
                                @(Html.Kendo().Grid<Adz.User.CMS.Models.CampaignModel.CampaignHistory>()
                                .Name("view_grid")
                                .Columns(columns =>
                                {
                                    columns.Bound(p => p.Campaign.Name);
                                    columns.Bound(p => p.DateTime).Format("{0:dd MMM yyyy}");
                                    columns.Bound(p => p.User.Email);
                                    //columns.Bound(p => p.Gender);
                                    //columns.Bound(p => p.Longitude).ClientTemplate(
                                    //    "<a class=\"a-hand-cursor\" onclick=\"fancyboxMap(#=Latitude#, #=Longitude#)\">View</a>").Title("Location").Filterable(filter => filter.Enabled(false));
                                })
                                .DataSource(dataSource => dataSource
                                    .Ajax()
                                    .PageSize(20)
                                    .Events(events => events.Error("error_handler"))
                                    .Read(read => read.Action("AdsViewPerformanceUsage_Read", "Reporting"))
                                )
                                                //.Events(events => events.DataBound("onDataBound").Change("onChange"))
                                .Filterable(filterable => filterable
                                    .Extra(false)
                                        .Operators(operators => operators
                                        .ForString(str => str.Clear()
                                            .StartsWith("Starts with")
                                            .Contains("Contains")
                                        ))
                                )
                                .Pageable(page => page
                                    .Refresh(true)
                                    .PageSizes(true)
                                )
                                                //.Scrollable(scr => scr.Height(280))
                                .Sortable(sortable => sortable
                                    .AllowUnsort(true)
                                    .SortMode(GridSortMode.MultipleColumn))
                                                //.Groupable()
                                .Resizable(resize => resize.Columns(true))
                                .Reorderable(reorder => reorder.Columns(true))
                                )
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                Ads Clicks History
                            </div>
                            <div class="panel-body" style="padding: 0;">
                                @(Html.Kendo().Grid<Adz.User.CMS.Models.CampaignModel.CampaignHistory>()
                                .Name("click_grid")
                                .Columns(columns =>
                                {
                                    columns.Bound(p => p.Campaign.Name);
                                    columns.Bound(p => p.DateTime).Format("{0:dd MMM yyyy}");
                                    columns.Bound(p => p.User.Email);
                                    //columns.Bound(p => p.Gender);
                                    //columns.Bound(p => p.Longitude).ClientTemplate(
                                    //    "<a class=\"a-hand-cursor\" onclick=\"fancyboxMap(#=Latitude#, #=Longitude#)\">View</a>").Title("Location").Filterable(filter => filter.Enabled(false));
                                })
                                .DataSource(dataSource => dataSource
                                    .Ajax()
                                    .PageSize(20)
                                    .Events(events => events.Error("error_handler"))
                                    .Read(read => read.Action("AdsClickPerformanceUsage_Read", "Reporting"))
                                )
                                        //.Events(events => events.DataBound("onDataBound").Change("onChange"))
                                .Filterable(filterable => filterable
                                    .Extra(false)
                                        .Operators(operators => operators
                                        .ForString(str => str.Clear()
                                            .StartsWith("Starts with")
                                            .Contains("Contains")
                                        ))
                                )
                                .Pageable(page => page
                                    .Refresh(true)
                                    .PageSizes(true)
                                )
                                        //.Scrollable(scr => scr.Height(280))
                                .Sortable(sortable => sortable
                                    .AllowUnsort(true)
                                    .SortMode(GridSortMode.MultipleColumn))
                                        //.Groupable()
                                .Resizable(resize => resize.Columns(true))
                                .Reorderable(reorder => reorder.Columns(true))
                                )
                            </div>
                        </div>
                    </div>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function fancybox(campaignid) {
        var parameter = "?campaignId=" + campaignid;
        $.fancybox.open({
            href: '@Url.Action("AdsPerfUsageByCampaign", "Reporting")'+parameter,
            type: 'iframe',
            padding: 0
        });
    }
</script>

<script type="text/javascript">
    function fancyboxMap(lat, lng) {
        var parameter = "?lat=" + lat + "&lng=" + lng;
        $.fancybox.open({
            href: '@Url.Action("GoogleMap", "Admin")'+parameter,
            type: 'iframe',
            padding: 0
        });
    }
</script>


<script type="text/javascript">
    function error_handler(e) {
        if (e.errors) {
            var result = "";
            var message = "";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message = this;
                    });
                }
            });
            if (message != "") {
                result = '<div class="alert alert-block alert-success">'
                + '<a class="close" data-dismiss="alert" href="#">X</a>'
                + '<h4 class="alert-heading">Error</h4>'
                + message
                + '</div>';

                $("#msgbox").html(result);
            }
        }
    }
</script>

<script type="text/javascript">
    function fancyboxHeatMap(campaign_id, action) {
        var parameter = "?parameter=" + campaign_id + "|" + action;
        console.log(parameter);
        $.fancybox.open({
            href: '@Url.Action("GoogleHeatMap", "Admin")'+parameter,
            type: 'iframe',
            padding: 0
        });
    }
</script>